eureka:
  client:
    service-url:
      defaultZone: http://admin:admin123@localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    prefer-ip-address: true
server:
  port: 8762
spring:
  application:
    name: microservice-peovider-user
  security:
    basic:
      enabled: true
    user:
      name: admin
      password: admin123