server:
  port: 8764
spring:
  application:
    name: microservice-consumer-movie-ribbon
eureka:
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#feign:
#  #熔断机制
#  hystrix:
#    enabled: true
