server:
  port: 8765
spring:
  application:
    name: microservice-consumer-movie-ribbon
eureka:
  client:
    #registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

microservice-peovider-user:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
#feign:
#  #熔断机制
#  hystrix:
#    enabled: true
