server:
  port: 8763
spring:
  application:
    name: microservice-consumer-movie
eureka:
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://admin:admin123@localhost:8761/eureka/
#feign:
#  #熔断机制
#  hystrix:
#    enabled: true
